// src/ArpEngine.h
#ifndef ARPENGINE_H
#define ARPENGINE_H

#include <string>
#include <vector>
#include <set>
#include <thread>
#include <atomic>
#include <mutex>
#include <shared_mutex>
#include <map>
#include <functional>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <iphlpapi.h>
#include <pcap.h>
#include <chrono>
#include "PacketHeaders.h"

#pragma comment(lib, "iphlpapi.lib")
#pragma comment(lib, "ws2_32.lib")

// ============================================================================
// Network Environment Info
// ============================================================================
struct NetworkInfo {
    std::string adapterType;
    std::string adapterDesc;
    std::string ssid;
    std::string subnetBase;
    int prefixLength = 24;
    uint32_t subnetMask = 0;
    bool dhcpEnabled = false;
    std::string dns1;
    std::string dns2;
    std::string linkSpeed;
    uint64_t linkSpeedBps = 0;
    std::string macAddress;
    int arpStormCounter = 0;
    bool broadcastStormDetected = false;
    
    // Interface bonding / LAG awareness
    bool isBonded = false;
    std::string bondMode;        // "LACP", "Static", "None"
    int bondMemberCount = 0;
    std::vector<std::string> bondMembers;  // adapter GUIDs of bond members
};

struct DeviceInfo {
    std::string ip;
    std::string mac;
    std::string hostname;
    std::string vendor;
    std::string firstSeen;
    std::string os;
    bool isPoisoned = false;
    bool isCut = false;
    bool isThrottled = false;
    bool isDelayed = false;
    bool isFake = false;      // Generated by ARP Flood
    bool isBlocked = false;   // auto-blocked by auto-block feature
    bool hasIpConflict = false; // duplicate IP but mismatched MAC
    std::string conflictMac;    // the conflicting MAC address
    std::chrono::system_clock::time_point lastSeenTime;
    
    // For sorting/display
    bool isGateway = false; 
};

// ARP restoration verification result
struct ArpRestoreResult {
    bool targetRestored = false;   // target received corrected packet
    bool gatewayRestored = false;  // gateway received corrected packet
    int  attemptsUsed = 0;
    std::string errorMsg;
};

// IP conflict report entry
struct IpConflictEntry {
    std::string ip;
    std::string mac1;    // first observed MAC
    std::string mac2;    // conflicting MAC
    std::chrono::system_clock::time_point detectedAt;
};

class ArpEngine {
public:
    ArpEngine();
    ~ArpEngine();

    bool initialize();
    void scanSubnet();
    std::vector<DeviceInfo> getDeviceList();
    bool isScanning() const { return m_scanning; }
    
    // Single-target poisoning
    void startSpoofing(const std::string& targetIp, const std::string& targetMac);
    void startVoidSpoofing(const std::string& targetIp, const std::string& targetMac);
    void stopSpoofing(const std::string& targetIp);
    void stopAllSpoofing();
    
    // Proper ARP table restore with verification
    ArpRestoreResult resetPoison(const std::string& targetIp);
    void resetAllPoison();
    bool isGatewayMacKnown() const { return m_gatewayMacKnown; }
    
    // Cache TTL configuration
    void setCacheTtlSeconds(int ttl) { m_cacheTtlSeconds = ttl; }
    int  getCacheTtlSeconds() const { return m_cacheTtlSeconds; }
    
    // ==================== NEW FEATURES ====================
    
    // Shield: protect own machine with gratuitous ARP defense
    void startShield();
    void stopShield();
    bool isShieldActive() const { return m_shieldActive; }

    // Poison All: ARP poison every device on the network
    void poisonAll();
    
    // Clear fake IPs generated by ARP flood
    void clearFakeDevices();
    
    // Turbo Mode: cut all others, claim full bandwidth for self
    void startTurboMode();
    void stopTurboMode();
    bool isTurboActive() const { return m_turboActive; }

    // Auto-Block: automatically block new devices that join the network
    void startAutoBlock();
    void stopAutoBlock();
    bool isAutoBlockActive() const { return m_autoBlockActive; }
    int  getBlockedCount() const;
    std::vector<std::string> getBlockedDevices() const;
    void unblockDevice(const std::string& ip);

    // =======================================================
    // ADVANCED FEATURES
    // =======================================================
    
    // DHCP starvation — exhaust DHCP pool to prevent new clients
    void startDhcpStarvation();
    void stopDhcpStarvation();
    bool isDhcpStarvationActive() const { return m_dhcpStarveActive; }
    int  getDhcpStarvePacketsSent() const { return m_dhcpStarveCount; }
    
    // ARP Flood / Broadcast Storm
    void startArpFlood();
    void stopArpFlood();
    bool isArpFloodActive() const { return m_arpFloodActive; }
    void setArpFloodRate(int rate) { m_arpFloodRate = rate; }
    int getArpFloodRate() const { return m_arpFloodRate; }
    
    // IP conflict detection — identify duplicate IPs on network
    std::vector<IpConflictEntry> getIpConflicts() const;
    int getIpConflictCount() const;
    
    // Gateway failover — detect and exploit redundant gateways
    std::vector<std::string> getSecondaryGateways() const;
    void poisonSecondaryGateway(const std::string& gwIp);
    void poisonAllGateways();
    
    // Broadcast storm detection — monitor for abnormal ARP traffic
    void setStormThreshold(uint32_t packetsPerSecond) { m_stormThreshold = packetsPerSecond; }
    uint32_t getStormThreshold() const { return m_stormThreshold; }
    uint32_t getCurrentArpRate() const { return m_netInfo.arpStormCounter; }
    
    // Interface bonding awareness — handle LAG configurations
    bool isInterfaceBonded() const { return m_netInfo.isBonded; }
    NetworkInfo getBondInfo() const { return m_netInfo; }

    // =======================================================
    
    std::string getLocalIp() const { return m_localIp; }
    std::string getGatewayIp() const { return m_gatewayIp; }
    std::string getAdapterName() const { return m_adapterName; }
    int getDeviceCount() const;

    NetworkInfo getNetworkInfo() const { return m_netInfo; }
    void setDeviceFlags(const std::string& ip, bool poisoned, bool cut, bool throttled, bool delayed);
    void updateDeviceHostname(const std::string& ip, const std::string& hostname, const std::string& os);

private:
    void listenerLoop();
    void spoofingLoop();
    void scanWorker();
    void shieldLoop();
    void sendArpRequest(pcap_t* handle, uint32_t targetIpNet);
    void sendArpReply(pcap_t* handle, uint32_t targetIpNet, const uint8_t* targetMac, uint32_t spoofIpNet);
    void sendArpReplyWithMac(pcap_t* handle, uint32_t targetIpNet, const uint8_t* targetMac, uint32_t senderIpNet, const uint8_t* senderMac);
    void sendGratuitousArp();
    std::string lookupVendor(const uint8_t mac[6]) const;
    void dhcpStarvationWorker();
    void arpFloodWorker();
    
    // ARP restoration verification helpers
    bool verifyArpEntry(const std::string& ip, const uint8_t expectedMac[6]);
    bool waitForArpReply(uint32_t targetIpNet, uint8_t* outMac, int timeoutMs);
    
    // Interface bonding detection
    void detectInterfaceBonding(IP_ADAPTER_ADDRESSES* adapter);
    
    void detectNetworkEnvironment(IP_ADAPTER_ADDRESSES* adapter);
    void detectWifiSSID();
    uint32_t prefixToMask(int prefixLength) const;

    std::atomic<bool> m_running;
    std::atomic<bool> m_scanning;
    std::thread m_listenerThread;
    std::thread m_spoofThread;
    std::thread m_scanThread;
    std::thread m_shieldThread;
    
    std::string m_localIp;
    std::string m_gatewayIp;
    std::string m_adapterName;
    std::string m_adapterGuid;
    uint32_t m_localIpNet;
    uint32_t m_gatewayIpNet;
    uint32_t m_subnetMask;
    int m_prefixLength;
    uint8_t m_localMac[6];
    uint8_t m_gatewayMac[6];
    bool m_gatewayMacKnown;
    
    pcap_t* m_recvHandle;
    pcap_t* m_sendHandle;

    std::map<std::string, DeviceInfo> m_devices;
    std::mutex m_devicesMutex;

    struct PoisonTarget {
        std::string ip;
        uint8_t mac[6];
        bool isVoid = false;
    };
    std::map<std::string, PoisonTarget> m_poisonTargets;
    std::recursive_mutex m_poisonMutex;  // recursive to prevent deadlock in nested lock scenarios

    NetworkInfo m_netInfo;

    // Shield state
    std::atomic<bool> m_shieldActive;

    // Turbo mode state
    std::atomic<bool> m_turboActive;

    // Auto-block state
    std::atomic<bool> m_autoBlockActive;
    std::set<std::string> m_knownDevices;    // IPs that were present when auto-block started
    std::set<std::string> m_blockedDevices;  // IPs that were auto-blocked
    std::mutex m_blockMutex;

    // Advanced capabilities
    std::atomic<bool> m_dhcpStarveActive;
    std::thread m_dhcpStarveThread;
    std::atomic<int> m_dhcpStarveCount{0};
    
    std::atomic<bool> m_arpFloodActive;
    std::thread m_arpFloodThread;
    std::atomic<int> m_arpFloodRate{10000}; // pkts/sec
    
    // Cache TTL (seconds) — devices not seen within this window get purged
    int m_cacheTtlSeconds = 300;
    
    // IP conflict tracking
    std::vector<IpConflictEntry> m_ipConflicts;
    mutable std::mutex m_conflictMutex;
    
    // Gateway failover & routing
    std::vector<std::string> m_secondaryGateways;
    mutable std::mutex m_gatewayMutex;

    // Storm detect
    std::atomic<uint32_t> m_arpPacketsPerSecond{0};
    std::atomic<uint32_t> m_stormThreshold{125}; // packets/sec threshold
    std::chrono::system_clock::time_point m_lastStormCheck;
};

#endif // ARPENGINE_H
